# base config
langs: [en, zh]
epoch: 200
update_every_epoch: 500
share_all_task_model: False
batch_size: 8 
save_interval: 20
dumpdir: /apdcephfs/share_1157259/users/baijunji/data/exp/tentrans/eyi32w/eyi_1gpu_8bsz2
patience: 10

sentenceRep:
  type: transformer
  pretrain_embedd: #/root/data/glove/glove.840B.300d.small.txt
  pretrain_rep:  /apdcephfs/share_1157259/users/baijunji/data/model/xlm_tentrans/model_xlm_tlm15.tt
  use_langembed: True

tasks:
  eyi_zhen: #task_id
    task_name: classification
    data:
        data_folder: /apdcephfs/share_1157259/users/baijunji/data/train_data/eyi_process/eyi_xlm/eyi_32w/
        src_vocab: vocab_xnli_15.v2
        train_valid_test: [train.csv, dev.csv, test.csv]
        feature: [seq1, lang1, label1]
        label1: [0, 1]
        group_by_size: False
        max_vocab: 95000
        max_len: 100
        
    lr_e: 0.000005
    lr_p: 0.000125
    target:
      sentence_rep_dim: 1024
      dropout: 0.1
  
  
