# base config
langs: [en]
epoch: 200
update_every_epoch: 200
share_all_task_model: False
batch_size: 1
save_interval: 20
dumpdir: ./data/exp/tentrans/sst2
patience: 20
sentenceRep:
      type: transformer 
      hidden_size: 512
      ff_size: 2048
      attention_dropout: 0.1
      encoder_layers: 6
      num_heads: 8
      embedd_size: 512
      dropout: 0.1
      learned_pos: True
      activation: relu


tasks:
  sst2_en:
    task_name: classification
    data:
        data_folder: ./data/train_data/sst2/
        src_vocab: tentrans.vocab
        train_valid_test: [dev.csv, dev.csv, dev.csv]
        label1: [0, 1]
        feature: [seq1, label1, lang1]
    lr_e: 0.00001
    lr_p: 0.00002
    target:
      sentence_rep_dim: 512
      dropout: 0.1
    weight_training: False
